name: clear_app_helper_isar
description: "Isar DB support of clear_app_helper"
version: 0.1.0
homepage: null
publish_to: none

isar_version: &isar_version 3.1.8

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  clear_app_helper:    
    # path: ../clear_app_helper
    git:
      url: https://github.com/sorewanya/clear_app_helper.git
      ref: main
  path_provider: ^2.1.5
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  file_picker: ^10.2.0
  get_it: ^8.0.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: 
    git:
      url: https://github.com/callumw-k/isar
      ref: v3
      path: packages/isar_generator
flutter:
